name: farmhelp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  appwrite: ^13.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.4
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  lottie: ^3.1.3
  pinput: ^2.2.31

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/facebook.svg
    - assets/icons/google.svg
    - assets/icons/apple-logo.svg
    - assets/images/signup-vector.svg
    - assets/.env
